Website edit
elemntorBootkamp/backend pull request #15
Opened 2023-06-26 10:06 UTC by shifraDomb

הפונקציה לא מתפקדת כמו שהיא תתפקד בהמשך כרגע זה רק בשביל שיהיה אפשר לקרוא לה מהצד לקוח

2023-06-27 23:10 UTC, chanakamin requested changes

2023-06-27 23:10 UTC, chanakamin commented on Routes/websiteRout.js
> +const express = require('express');
correct the file name

2023-06-27 23:10 UTC, chanakamin commented on Routes/websiteRout.js
> +const websiterout = express.Router();
why require and not import?

2023-06-27 23:10 UTC, chanakamin commented on Routes/websiteRout.js
> +const websiterout = express.Router();
websiteRoute

2023-06-27 23:10 UTC, chanakamin commented on controllers/websitController.js
> +let allwebsite = [];
correct the file name

2023-06-29 09:15 UTC, shifraDomb commented on Routes/websiteRout.js
> +const websiterout = express.Router();
העלתי commit נוסף עם import & export

2023-07-02 09:05 UTC, chanakamin approved these changes

2023-07-03 10:27 UTC, YehudisSternberg approved these changes

2023-07-03 10:27 UTC, merged